/* SimParam.h */
#ifndef SIMULATION_PARAMETERS_H
#define SIMULATION_PARAMETERS_H
#define NUM_TASK_GENERATORS 1
#define NUM_TASKS_PER_GEN 30
#define NUM_TASK_HANDLERS 1
#define TOTAL_NUM_TASKS (NUM_TASKS_PER_GEN * NUM_TASK_GENERATORS)
#define TASKS_PER_LINE 5
#define PRI_QUEUE_CAPACITY 10
#define PLUS_INF INT_MAX
#define MAX_ROUND 1000
#endif